name: elegance
on:
  push:
    branches:
      - feature/add-deploy
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.19.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Hero theme cli
        run: npm i -g @herospark/hero-themes-cli

      - name: Deploy staging
        run: hero t:deployci --env=staging
